#include "graph_codegen_runner.h"
#include "graph_store.h"

#include <QDir>
#include <QEventLoop>
#include <QFile>
#include <QHostAddress>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QProcess>
#include <QProcessEnvironment>
#include <QSignalSpy>
#include <QStandardPaths>
#include <QTcpServer>
#include <QTemporaryDir>
#include <QtTest>

using namespace Hypr;
using Json::Value;

namespace {

QString findNode()
{
    const auto override = QProcessEnvironment::systemEnvironment().value(QStringLiteral("HYPRACCEL_NODE"));
    if (!override.isEmpty()) return override;
    return QStandardPaths::findExecutable(QStringLiteral("node"));
}

// node <script> <in> <out>, returns {ok, stdout, stderr, exitCode, source}.
struct OracleResult { bool ok; QString stdOut; QString stdErr; int exitCode; QString source; };

OracleResult runOracle(const QString &graphJsonPath)
{
    OracleResult r{ false, {}, {}, -1, {} };
    QTemporaryDir dir;
    if (!dir.isValid()) return r;
    const QString inPath = dir.filePath(QStringLiteral("graph.json"));
    QFile::copy(graphJsonPath, inPath);
    const QString outPath = dir.filePath(QStringLiteral("graph.c"));
    QProcess process;
    process.start(findNode(), { QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE), inPath, outPath });
    if (!process.waitForFinished(15000)) return r;
    r.exitCode = process.exitCode();
    r.stdOut = QString::fromUtf8(process.readAllStandardOutput());
    r.stdErr = QString::fromUtf8(process.readAllStandardError()).trimmed();
    if (r.exitCode == 0) {
        QFile f(outPath);
        if (f.open(QIODevice::ReadOnly)) { r.source = QString::fromUtf8(f.readAll()); r.ok = true; }
    }
    return r;
}

} // namespace

class GraphCodegenRunnerTest : public QObject {
    Q_OBJECT
private Q_SLOTS:

    void unavailableWhenScriptMissing()
    {
        GraphCodegenRunner runner(QStringLiteral("/nonexistent/graph_to_c.js"));
        GraphCodegenResult result = runner.generateSync(Value::fromObject({}));
        QVERIFY(!result.ok);
        QVERIFY(!result.unavailableReason.isEmpty());
    }

    void syncGenerateProducesC()
    {
        if (findNode().isEmpty()) QSKIP("node not found");
        QString err;
        Value graph = Json::parse(readFile(QStringLiteral(DEMO_PROJECT_FIXTURE) + QStringLiteral("/graphs/GRAPH_1.json")), &err);
        QVERIFY2(err.isEmpty(), qPrintable(err));

        GraphCodegenRunner runner(QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE));
        GraphCodegenResult result = runner.generateSync(graph);
        QVERIFY2(result.unavailableReason.isEmpty(), qPrintable(result.unavailableReason));
        QVERIFY(result.ok);
        QCOMPARE(result.exitCode, 0);
        QVERIFY(result.source.contains(QStringLiteral("Generated by HyprAccel MBD-T3 graph_to_c.js from graph.json.")));
    }

    void asyncGenerateEmitsFinished()
    {
        if (findNode().isEmpty()) QSKIP("node not found");
        Value graph = Json::parse(readFile(QStringLiteral(DEMO_PROJECT_FIXTURE) + QStringLiteral("/graphs/GRAPH_1.json")));

        GraphCodegenRunner runner(QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE));
        QSignalSpy spy(&runner, &GraphCodegenRunner::finished);
        runner.generate(graph);
        QVERIFY(spy.wait(15000));
        const auto result = qvariant_cast<GraphCodegenResult>(spy.first().first());
        QVERIFY(result.ok);
    }

    // --- Required: desktop output == node graph_to_c.js on a graph.json
    // copy, for every demo graph and the schema examples. ---
    void parityAgainstNodeOracle_data()
    {
        QTest::addColumn<QString>("path");
        const QDir demoGraphs(QStringLiteral(DEMO_PROJECT_FIXTURE) + QStringLiteral("/graphs"));
        for (const auto &f : demoGraphs.entryList({ "*.json" }, QDir::Files))
            QTest::newRow(qPrintable(f)) << demoGraphs.filePath(f);
        QTest::newRow("pid_test.json") << QString(QStringLiteral(TEST_GRAPHS_DIR_FIXTURE) + QStringLiteral("/pid_test.json"));
    }

    void parityAgainstNodeOracle()
    {
        if (findNode().isEmpty()) QSKIP("node not found");
        QFETCH(QString, path);

        QString err;
        Value graph = Json::parse(readFile(path), &err);
        QVERIFY2(err.isEmpty(), qPrintable(err));

        GraphCodegenRunner runner(QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE));
        GraphCodegenResult desktop = runner.generateSync(graph);
        OracleResult oracle = runOracle(path);

        QCOMPARE(desktop.ok, oracle.ok);
        if (desktop.ok) {
            QCOMPARE(desktop.source, oracle.source);
        } else {
            QCOMPARE(desktop.stdErr, oracle.stdErr);
        }
    }

    // --- Required: a failing graph surfaces the same error text as the
    // server (a missing required input edge). ---
    void failingGraphMatchesServerErrorText()
    {
        if (findNode().isEmpty()) QSKIP("node not found");

        Json::Object node;
        Json::set(node, QStringLiteral("id"), Value::fromString(QStringLiteral("pub1")));
        Json::set(node, QStringLiteral("type"), Value::fromString(QStringLiteral("Publish")));
        Json::set(node, QStringLiteral("label"), Value::fromString(QStringLiteral("Publish pub1")));
        Json::Object params;
        Json::set(params, QStringLiteral("topic"), Value::fromString(QStringLiteral("t")));
        Json::set(params, QStringLiteral("transport"), Value::fromString(QStringLiteral("telemetry")));
        Json::set(params, QStringLiteral("retain"), Value::fromBool(false));
        Json::set(node, QStringLiteral("params"), Value::fromObject(params));
        Json::Object pos;
        Json::set(pos, QStringLiteral("x"), Value::fromNumber(0));
        Json::set(pos, QStringLiteral("y"), Value::fromNumber(0));
        Json::set(node, QStringLiteral("position"), Value::fromObject(pos));

        Json::Object root;
        Json::set(root, QStringLiteral("format"), Value::fromString(QStringLiteral("hypraccel.mbd.graph")));
        Json::set(root, QStringLiteral("version"), Value::fromNumber(1));
        Json::set(root, QStringLiteral("id"), Value::fromString(QStringLiteral("bad_graph")));
        Json::set(root, QStringLiteral("name"), Value::fromString(QStringLiteral("Bad Graph")));
        Json::set(root, QStringLiteral("nodes"), Value::fromArray({ Value::fromObject(node) }));
        Json::set(root, QStringLiteral("edges"), Value::fromArray({}));
        Json::set(root, QStringLiteral("inputs"), Value::fromArray({}));
        Json::set(root, QStringLiteral("metadata"), Value::fromObject({}));
        Value graph = Value::fromObject(root);

        GraphCodegenRunner runner(QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE));
        GraphCodegenResult desktop = runner.generateSync(graph);
        QVERIFY(!desktop.ok);
        QVERIFY(desktop.unavailableReason.isEmpty()); // this is a graph error, not a tooling failure
        QCOMPARE(desktop.exitCode, 1);
        QVERIFY(desktop.stdErr.startsWith(QStringLiteral("graph_to_c: ")));

        QTemporaryDir dir;
        QVERIFY(dir.isValid());
        const QString inPath = dir.filePath(QStringLiteral("graph.json"));
        QFile f(inPath);
        QVERIFY(f.open(QIODevice::WriteOnly));
        f.write(Json::stringify(graph));
        f.close();
        OracleResult oracle = runOracle(inPath);
        QVERIFY(!oracle.ok);
        QCOMPARE(desktop.stdErr, oracle.stdErr);

        // Server behaviour for this same case (server.js /api/build:
        // `res.status(422).json({ error: err.stderr.trim() })`) is exactly
        // desktop.stdErr; see checkAgainstRealServerBuild() for the live
        // confirmation.
    }

    // --- Required: desktop output == the `source` from a real
    // POST /api/build against the web server, for graphs where the
    // server's hardware validation passes. Reports which graphs were
    // skipped and why. ---
    void parityAgainstRealServerBuild()
    {
        if (findNode().isEmpty()) QSKIP("node not found");
        if (!QDir(QStringLiteral(MBD_EDITOR_DIR_FIXTURE) + QStringLiteral("/node_modules")).exists())
            QSKIP("mbd/editor/node_modules missing");

        QTemporaryDir dir;
        QVERIFY(dir.isValid());
        const QString projectId = QStringLiteral("demo_project");
        QVERIFY(copyRecursively(QStringLiteral(DEMO_PROJECT_FIXTURE), dir.filePath(projectId)));

        quint16 port = 0;
        {
            QTcpServer probe;
            QVERIFY(probe.listen(QHostAddress::LocalHost, 0));
            port = probe.serverPort();
        }
        QProcess server;
        QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
        env.insert(QStringLiteral("HYPRACCEL_PROJECTS_ROOT"), dir.path());
        env.insert(QStringLiteral("HYPRACCEL_EDITOR_PORT"), QString::number(port));
        server.setProcessEnvironment(env);
        server.setWorkingDirectory(QStringLiteral(MBD_EDITOR_DIR_FIXTURE));
        server.start(findNode(), { QStringLiteral(MBD_EDITOR_DIR_FIXTURE) + QStringLiteral("/server.js") });
        if (!server.waitForStarted(5000)) QSKIP("server did not start");
        QTest::qWait(400); // let express bind

        QNetworkAccessManager nam;
        const QDir graphsDir(dir.filePath(projectId + QStringLiteral("/graphs")));
        int checked = 0, skipped = 0;
        for (const auto &filename : graphsDir.entryList({ "*.json" }, QDir::Files)) {
            const QString graphId = filename.left(filename.size() - 5);
            const QUrl url(QStringLiteral("http://127.0.0.1:%1/api/build?projectId=%2&graphId=%3")
                                .arg(port).arg(projectId, graphId));
            QNetworkRequest req(url);
            QNetworkReply *reply = nam.post(req, QByteArray("{}"));
            QEventLoop loop;
            QObject::connect(reply, &QNetworkReply::finished, &loop, &QEventLoop::quit);
            loop.exec();
            const QByteArray body = reply->readAll();
            const auto doc = QJsonDocument::fromJson(body);
            const int status = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
            reply->deleteLater();

            if (status != 200) {
                ++skipped;
                qInfo() << "skip server parity for" << graphId << ": server rejected build:" << doc.object().value("error").toString();
                continue;
            }
            const QString serverSource = doc.object().value("source").toString();

            Value graph = Json::parse(readFile(graphsDir.filePath(filename)));
            GraphCodegenRunner runner(QStringLiteral(GRAPH_TO_C_SCRIPT_FIXTURE));
            GraphCodegenResult desktop = runner.generateSync(graph);
            QVERIFY(desktop.ok);
            QCOMPARE(desktop.source, serverSource);
            ++checked;
        }
        qInfo() << "server-build parity: checked" << checked << "skipped" << skipped;
        QVERIFY(checked > 0);

        server.terminate();
        if (!server.waitForFinished(2000)) server.kill();
    }

private:
    static QByteArray readFile(const QString &path)
    {
        QFile f(path);
        f.open(QIODevice::ReadOnly);
        return f.readAll();
    }

    static bool copyRecursively(const QString &srcPath, const QString &dstPath)
    {
        QDir src(srcPath);
        if (!src.exists()) return false;
        QDir().mkpath(dstPath);
        for (const auto &entry : src.entryInfoList(QDir::Files | QDir::NoDotAndDotDot | QDir::Dirs)) {
            const QString target = QDir(dstPath).filePath(entry.fileName());
            if (entry.isDir()) {
                if (!copyRecursively(entry.filePath(), target)) return false;
            } else {
                if (!QFile::copy(entry.filePath(), target)) return false;
            }
        }
        return true;
    }
};

QTEST_MAIN(GraphCodegenRunnerTest)
#include "graph_codegen_runner_test.moc"
