#!/usr/bin/env node

/**
 * gen_board_config.js — HyprAccel CORE-T3
 *
 * Generates a C header (hyp_board_config.h) from boards.yaml
 * for a specific target board.
 *
 * Usage: node gen_board_config.js <target_board> <path_to_boards.yaml> <out_dir>
 */

const fs = require('fs');
const path = require('path');

function parseSimpleYaml(content) {
    const lines = content.split('\n');
    const result = { boards: {} };
    let currentBoard = null;
    let currentCategory = null;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].split('#')[0].trimEnd();
        if (line.trim().length === 0) continue;

        // Naive indentation-based parsing for our specific boards.yaml structure
        const indent = line.search(/\S/);
        const trimmed = line.trim();

        if (indent === 0 && trimmed === 'boards:') continue;
        
        if (indent === 2 && trimmed.endsWith(':')) {
            currentBoard = trimmed.slice(0, -1);
            result.boards[currentBoard] = { 
                accelerators: [], 
                pins: { gpio: [], spi: {}, i2c: {}, uart: {}, pwm: [], adc: [] } 
            };
            currentCategory = null;
            continue;
        }

        if (indent === 4 && currentBoard) {
            if (trimmed.endsWith(':')) {
                currentCategory = trimmed.slice(0, -1);
            } else if (trimmed.includes(':')) {
                const [key, ...rest] = trimmed.split(':');
                let val = rest.join(':').trim();
                if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
                else if (!isNaN(Number(val))) val = Number(val);
                result.boards[currentBoard][key.trim()] = val;
            }
            continue;
        }

        if (indent === 6 && currentBoard && currentCategory) {
            if (trimmed.startsWith('- "')) {
                const val = trimmed.slice(3, -1);
                if (currentCategory === 'accelerators') {
                    result.boards[currentBoard].accelerators.push(val);
                } else if (currentCategory === 'gpio' || currentCategory === 'pwm' || currentCategory === 'adc') {
                    result.boards[currentBoard].pins[currentCategory].push(val);
                }
            } else if (trimmed.includes(': {')) {
                // e.g. spi0: { sck: "SPI0CLK", ... }
                const [key, valStr] = trimmed.split(': {');
                const cleanValStr = valStr.replace('}', '').trim();
                const pairs = cleanValStr.split(',').map(s => s.trim());
                const obj = {};
                for (const pair of pairs) {
                    let [k, v] = pair.split(':');
                    k = k.trim();
                    v = v.trim();
                    if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
                    obj[k] = v;
                }
                result.boards[currentBoard].pins[currentCategory][key.trim()] = obj;
            }
        }
    }
    return result;
}

function generateHeader(boardKey, boardData) {
    let out = `/*
 * hyp_board_config.h
 *
 * Generated by HyprAccel CORE-T3 codegen.
 * Target Board: ${boardData.name || boardKey}
 * Architecture: ${boardData.architecture || 'Unknown'}
 */

#ifndef HYP_BOARD_CONFIG_H
#define HYP_BOARD_CONFIG_H

#define HYP_BOARD_NAME "${boardData.name || boardKey}"
#define HYP_BOARD_ARCH_${(boardData.architecture || '').toUpperCase().replace(/-/g, '_')} 1
#define HYP_SYSCLK_MHZ ${boardData.clock_freq_mhz || 0}

/* Transport Configuration */
`;

    if (boardData.fpga_transport) {
        out += `#define HYP_FPGA_TRANSPORT_TYPE "${boardData.fpga_transport}"\n`;
        out += `#define HYP_FPGA_TRANSPORT_${boardData.fpga_transport.toUpperCase()} 1\n`;
    }

    out += `\n/* Hardware Accelerators */\n`;
    if (boardData.accelerators && boardData.accelerators.length > 0) {
        for (const acc of boardData.accelerators) {
            out += `#define HYP_HAS_HW_${acc.toUpperCase()} 1\n`;
        }
    } else {
        out += `/* No hardware accelerators defined */\n`;
    }

    out += `\n/* 
 * Pin Definitions
 * (These will be populated by MBD-T1b during node graph synthesis.
 * For now, they are available in the schema for UI mapping.)
 */\n`;

    out += `\n#endif /* HYP_BOARD_CONFIG_H */\n`;
    return out;
}

function main() {
    const args = process.argv.slice(2);
    if (args.length < 3) {
        console.error("Usage: node gen_board_config.js <target_board> <boards.yaml> <out_dir>");
        process.exit(1);
    }

    const targetBoard = args[0];
    const yamlPath = args[1];
    const outDir = args[2];

    if (!fs.existsSync(yamlPath)) {
        console.error(`Error: File ${yamlPath} not found.`);
        process.exit(1);
    }

    const yamlContent = fs.readFileSync(yamlPath, 'utf8');
    const parsed = parseSimpleYaml(yamlContent);

    if (!parsed.boards[targetBoard]) {
        console.error(`Error: Board '${targetBoard}' not found in ${yamlPath}.`);
        console.error(`Available boards: ${Object.keys(parsed.boards).join(', ')}`);
        process.exit(1);
    }

    const headerContent = generateHeader(targetBoard, parsed.boards[targetBoard]);
    
    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    const outPath = path.join(outDir, 'hyp_board_config.h');
    fs.writeFileSync(outPath, headerContent, 'utf8');

    console.log(`Successfully generated ${outPath} for ${targetBoard}`);
}

main();
