#!/usr/bin/env node

/**
 * gen_board_config.js — HyprAccel CORE-T3
 *
 * Generates a C header (hyp_board_config.h) from boards.yaml
 * for a specific target board.
 *
 * Usage: node gen_board_config.js <target_board> <path_to_boards.yaml> <out_dir>
 *
 * FW-P1..P6: Also emits per-signal pin macros so the runtime can resolve
 * physical pin numbers from generated configuration rather than hardcoded values.
 *
 * Emitted macro families:
 *   HYP_RESOURCE_SPI_HSPI                  — bus enabled (1)
 *   HYP_RESOURCE_SPI_HSPI_SCK_PIN   14    — physical GPIO number (int)
 *   HYP_RESOURCE_SPI_HSPI_MOSI_PIN  13
 *   HYP_RESOURCE_SPI_HSPI_MISO_PIN  12
 *   HYP_RESOURCE_SPI_HSPI_CS_PIN    15
 *   HYP_RESOURCE_I2C_I2C0_SDA_PIN   21
 *   HYP_RESOURCE_I2C_I2C0_SCL_PIN   22
 *   HYP_RESOURCE_UART_UART0_TX_PIN   1
 *   HYP_RESOURCE_UART_UART0_RX_PIN   3
 *   HYP_RESOURCE_PWM_GPIO25_PIN      25   — canonical output pin number
 *   HYP_RESOURCE_ADC_GPIO32_PIN      32   — canonical input pin number
 *   HYP_RESOURCE_GPIO_GPIO4_PIN       4   — canonical GPIO pin number
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const { readProjectConfig } = require('./project_config');
const { checkPinConflicts } = require('./pin_conflicts');
const { injectProjectDefines } = require('./project_defines');

/**
 * Extract a GPIO number from a string such as "GPIO14" -> 14.
 * Returns -1 when the format is not recognised.
 */
function gpioNum(pinStr) {
    if (!pinStr || typeof pinStr !== 'string') return -1;
    const m = pinStr.match(/^GPIO(\d+)$/i);
    return m ? parseInt(m[1], 10) : -1;
}


function generateHeader(boardKey, boardData) {
    let out = `/*
 * hyp_board_config.h
 *
 * Generated by HyprAccel CORE-T3 codegen.
 * Target Board: ${boardData.name || boardKey}
 * Architecture: ${boardData.architecture || 'Unknown'}
 *
 * FW-P1..P6: Per-signal pin macros are emitted for every bus resource defined
 * in boards.yaml so that hyp_esp32_hw.cpp can initialise peripherals from this
 * generated configuration rather than hardcoded constants.
 */

#ifndef HYP_BOARD_CONFIG_H
#define HYP_BOARD_CONFIG_H

#define HYP_BOARD_NAME "${boardData.name || boardKey}"
#define HYP_BOARD_ARCH_${(boardData.architecture || '').toUpperCase().replace(/-/g, '_')} 1
#define HYP_SYSCLK_MHZ ${boardData.clock_freq_mhz || 0}

/* Transport Configuration */
`;

    if (boardData.fpga_transport) {
        out += `#define HYP_FPGA_TRANSPORT_TYPE "${boardData.fpga_transport}"\n`;
        out += `#define HYP_FPGA_TRANSPORT_${boardData.fpga_transport.toUpperCase()} 1\n`;
    }

    out += `\n/* Hardware Accelerators */\n`;
    if (boardData.accelerators && boardData.accelerators.length > 0) {
        for (const acc of boardData.accelerators) {
            out += `#define HYP_HAS_HW_${acc.toUpperCase()} 1\n`;
        }
    } else {
        out += `/* No hardware accelerators defined */\n`;
    }

    const pins = boardData.pins || {};

    // -------------------------------------------------------------------------
    // SPI bus pin macros (FW-P3)
    // -------------------------------------------------------------------------
    const spiEntries = Object.entries(pins.spi || {});
    if (spiEntries.length > 0) {
        out += `\n/* SPI Bus Pin Definitions (FW-P3) */\n`;
        for (const [inst, signals] of spiEntries) {
            const macro = `HYP_RESOURCE_SPI_${inst.toUpperCase()}`;
            out += `#define ${macro} 1\n`;
            for (const [role, pin] of Object.entries(signals)) {
                const num = gpioNum(pin);
                if (num >= 0) {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN ${num}  /* ${pin} */\n`;
                } else {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN_STR "${pin}"\n`;
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // I2C bus pin macros (FW-P4)
    // -------------------------------------------------------------------------
    const i2cEntries = Object.entries(pins.i2c || {});
    if (i2cEntries.length > 0) {
        out += `\n/* I2C Bus Pin Definitions (FW-P4) */\n`;
        /* Collected across all buses; emitted as one runtime lookup table macro. */
        const i2cDeviceRows = [];
        for (const [inst, signals] of i2cEntries) {
            const macro = `HYP_RESOURCE_I2C_${inst.toUpperCase()}`;
            out += `#define ${macro} 1\n`;
            for (const [role, pin] of Object.entries(signals)) {
                /* "devices" is a nested map of named slaves, not a pin signal. */
                if (role === 'devices') continue;
                const num = gpioNum(pin);
                if (num >= 0) {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN ${num}  /* ${pin} */\n`;
                } else {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN_STR "${pin}"\n`;
                }
            }
            /* SDK-T6: per-device 7-bit slave address macros. Resource IDs of the
             * form "i2c.<device>" resolve to (this bus + the device address). */
            for (const [devName, devCfg] of Object.entries(signals.devices || {})) {
                const addr = devCfg && devCfg.address;
                if (addr === undefined || addr === null) continue;
                const addrNum = (typeof addr === 'string') ? parseInt(addr, 16) : addr;
                const addrHex = `0x${addrNum.toString(16).toUpperCase().padStart(2, '0')}`;
                const devMacro = `HYP_RESOURCE_I2C_${devName.toUpperCase()}`;
                out += `#define ${devMacro} 1\n`;
                out += `#define ${devMacro}_ADDRESS ${addrHex}  /* device "${devName}" on ${inst} */\n`;
                i2cDeviceRows.push(`    { "${devName.toLowerCase()}", ${devMacro}_ADDRESS }`);
            }
        }
        if (i2cDeviceRows.length > 0) {
            out += `\n/* I2C Device Address Table (SDK-T6): semantic device name -> 7-bit slave address.\n`;
            out += ` * Consumed by the runtime to build hyp_i2c_device_table[]. */\n`;
            out += `#define HYP_I2C_DEVICE_TABLE \\\n${i2cDeviceRows.join(', \\\n')}\n`;
        }
    }

    // -------------------------------------------------------------------------
    // UART pin macros (FW-P2)
    // -------------------------------------------------------------------------
    const uartEntries = Object.entries(pins.uart || {});
    if (uartEntries.length > 0) {
        out += `\n/* UART Pin Definitions (FW-P2) */\n`;
        for (const [inst, signals] of uartEntries) {
            const macro = `HYP_RESOURCE_UART_${inst.toUpperCase()}`;
            out += `#define ${macro} 1\n`;
            for (const [role, pin] of Object.entries(signals)) {
                const num = gpioNum(pin);
                if (num >= 0) {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN ${num}  /* ${pin} */\n`;
                } else {
                    out += `#define ${macro}_${role.toUpperCase()}_PIN_STR "${pin}"\n`;
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // PWM pin macros (FW-P5)
    // -------------------------------------------------------------------------
    if ((pins.pwm || []).length > 0) {
        out += `\n/* PWM Pin Definitions (FW-P5) */\n`;
        for (const pin of pins.pwm) {
            const macro = `HYP_RESOURCE_PWM_${pin.toUpperCase()}`;
            const num = gpioNum(pin);
            if (num >= 0) {
                out += `#define ${macro} 1\n`;
                out += `#define ${macro}_PIN ${num}  /* ${pin} */\n`;
            }
        }
    }

    // -------------------------------------------------------------------------
    // ADC pin macros (FW-P6)
    // -------------------------------------------------------------------------
    if ((pins.adc || []).length > 0) {
        out += `\n/* ADC Pin Definitions (FW-P6) */\n`;
        for (const pin of pins.adc) {
            const macro = `HYP_RESOURCE_ADC_${pin.toUpperCase()}`;
            const num = gpioNum(pin);
            if (num >= 0) {
                out += `#define ${macro} 1\n`;
                out += `#define ${macro}_PIN ${num}  /* ${pin} */\n`;
            }
        }
    }

    // -------------------------------------------------------------------------
    // GPIO capability macros (FW-P1)
    // -------------------------------------------------------------------------
    if ((pins.gpio || []).length > 0) {
        out += `\n/* GPIO Pin Definitions (FW-P1) */\n`;
        for (const pin of pins.gpio) {
            const macro = `HYP_RESOURCE_GPIO_${pin.toUpperCase()}`;
            const num = gpioNum(pin);
            if (num >= 0) {
                out += `#define ${macro} 1\n`;
                out += `#define ${macro}_PIN ${num}  /* ${pin} */\n`;
            }
        }
    }

    out += `\n/*\n * Project Pin Assignments\n * (Augmented by MBD-T1b during node graph synthesis with\n * HYP_PIN_* and HYP_PERIPH_* defines for configured hardware resources.)\n */\n`;
    out += `\n#endif /* HYP_BOARD_CONFIG_H */\n`;
    return out;
}

/**
 * --project <projectDir>: reads the project's merged hardware+clock config,
 * validates the project's board matches <target_board>, checks for pin
 * conflicts (no graphs are known to the CLI, so graphs = []), and injects the
 * project's macros ('materialize' variant, matching mbd/editor/server.js
 * materializeEsp32) into the generated header text.
 */
function applyProjectConfig(headerContent, targetBoard, boardData, projectDir, yamlPath) {
    const config = readProjectConfig(projectDir, yamlPath);
    if (config.board !== targetBoard) {
        console.error(`Error: Project board '${config.board}' does not match target board '${targetBoard}'.`);
        process.exit(1);
    }
    const { errors, warnings } = checkPinConflicts(config, boardData, []);
    if (errors.length > 0) {
        for (const issue of errors) console.error(issue.message);
        process.exit(1);
    }
    const warningMessages = warnings.map(issue => issue.message);
    return injectProjectDefines(headerContent, config, boardData, { variant: 'materialize', warnings: warningMessages });
}

function main() {
    const args = process.argv.slice(2);
    if (args.length < 3) {
        console.error("Usage: node gen_board_config.js <target_board> <boards.yaml> <out_dir> [--project <projectDir>]");
        process.exit(1);
    }

    const targetBoard = args[0];
    const yamlPath = args[1];
    const outDir = args[2];
    let projectDir = null;
    const projectFlagIndex = args.indexOf('--project');
    if (projectFlagIndex !== -1) {
        projectDir = args[projectFlagIndex + 1];
        if (!projectDir) {
            console.error('Error: --project requires a project directory argument.');
            process.exit(1);
        }
    }

    if (!fs.existsSync(yamlPath)) {
        console.error(`Error: File ${yamlPath} not found.`);
        process.exit(1);
    }

    const yamlContent = fs.readFileSync(yamlPath, 'utf8');
    const parsed = yaml.load(yamlContent);

    if (!parsed.boards[targetBoard]) {
        console.error(`Error: Board '${targetBoard}' not found in ${yamlPath}.`);
        console.error(`Available boards: ${Object.keys(parsed.boards).join(', ')}`);
        process.exit(1);
    }

    let headerContent = generateHeader(targetBoard, parsed.boards[targetBoard]);
    if (projectDir) {
        headerContent = applyProjectConfig(headerContent, targetBoard, parsed.boards[targetBoard], projectDir, yamlPath);
    }

    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    const outPath = path.join(outDir, 'hyp_board_config.h');
    fs.writeFileSync(outPath, headerContent, 'utf8');

    console.log(`Successfully generated ${outPath} for ${targetBoard}`);
}

if (require.main === module) {
    main();
}

module.exports = { generateHeader };
