/*
 * hyp_board_config.h
 *
 * Generated by HyprAccel CORE-T3 codegen.
 * Target Board: THEJAS32 (ARIES v2.0)
 * Architecture: riscv32
 */

#ifndef HYP_BOARD_CONFIG_H
#define HYP_BOARD_CONFIG_H

#define HYP_BOARD_NAME "THEJAS32 (ARIES v2.0)"
#define HYP_BOARD_ARCH_RISCV32 1
#define HYP_SYSCLK_MHZ 100

/* Transport Configuration */
#define HYP_FPGA_TRANSPORT_TYPE "SPI"
#define HYP_FPGA_TRANSPORT_SPI 1

/* Hardware Accelerators */
#define HYP_HAS_HW_CORDIC 1

/* 
 * Pin Definitions
 * (These will be populated by MBD-T1b during node graph synthesis.
 * For now, they are available in the schema for UI mapping.)
 */


/* MBD Pin Assignments — generated by pin_config UI (MBD-T1b) */
#define HYP_PIN_SENSORINPUT_1__DATA "SPI1MOSI"  /* SensorInput[1] → spi.spi1.data */

#endif /* HYP_BOARD_CONFIG_H */
