/*
 * hyp_board_config.h
 *
 * Generated by HyprAccel CORE-T3 codegen.
 * Target Board: ESP32 (WROOM-32)
 * Architecture: xtensa-lx6
 */

#ifndef HYP_BOARD_CONFIG_H
#define HYP_BOARD_CONFIG_H

#define HYP_BOARD_NAME "ESP32 (WROOM-32)"
#define HYP_BOARD_ARCH_XTENSA_LX6 1
#define HYP_SYSCLK_MHZ 240

/* Transport Configuration */
#define HYP_FPGA_TRANSPORT_TYPE "SPI"
#define HYP_FPGA_TRANSPORT_SPI 1

/* Hardware Accelerators */
#define HYP_HAS_HW_CORDIC 1

/* 
 * Pin Definitions
 * (These will be populated by MBD-T1b during node graph synthesis.
 * For now, they are available in the schema for UI mapping.)
 */

#endif /* HYP_BOARD_CONFIG_H */
